[2023-07-20T11:45:13.290+0000] {processor.py:153} INFO - Started process (PID=1579) to work on /opt/airflow/dags/main.py
[2023-07-20T11:45:13.292+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T11:45:13.294+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:45:13.294+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T11:45:13.377+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:45:13.373+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 4, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T11:45:13.379+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T11:45:13.401+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.117 seconds
[2023-07-20T11:45:43.477+0000] {processor.py:153} INFO - Started process (PID=1612) to work on /opt/airflow/dags/main.py
[2023-07-20T11:45:43.480+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T11:45:43.482+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:45:43.481+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T11:45:43.520+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:45:43.517+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 4, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T11:45:43.521+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T11:45:43.546+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.075 seconds
[2023-07-20T11:46:13.751+0000] {processor.py:153} INFO - Started process (PID=1659) to work on /opt/airflow/dags/main.py
[2023-07-20T11:46:13.753+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T11:46:13.754+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:46:13.754+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T11:46:13.785+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:46:13.782+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 4, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T11:46:13.786+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T11:46:13.808+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.060 seconds
[2023-07-20T11:46:43.937+0000] {processor.py:153} INFO - Started process (PID=1692) to work on /opt/airflow/dags/main.py
[2023-07-20T11:46:43.941+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T11:46:43.943+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:46:43.942+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T11:46:43.979+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:46:43.976+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 4, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T11:46:43.981+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T11:46:44.001+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.068 seconds
[2023-07-20T11:47:14.121+0000] {processor.py:153} INFO - Started process (PID=1739) to work on /opt/airflow/dags/main.py
[2023-07-20T11:47:14.124+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T11:47:14.126+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:47:14.126+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T11:47:14.167+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:47:14.164+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 4, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T11:47:14.169+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T11:47:14.195+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.078 seconds
[2023-07-20T11:47:44.339+0000] {processor.py:153} INFO - Started process (PID=1772) to work on /opt/airflow/dags/main.py
[2023-07-20T11:47:44.342+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T11:47:44.344+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:47:44.344+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T11:47:44.382+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:47:44.379+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 4, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T11:47:44.383+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T11:47:44.409+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.075 seconds
[2023-07-20T11:48:14.591+0000] {processor.py:153} INFO - Started process (PID=1819) to work on /opt/airflow/dags/main.py
[2023-07-20T11:48:14.594+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T11:48:14.597+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:48:14.597+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T11:48:14.640+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:48:14.636+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 4, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T11:48:14.642+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T11:48:14.670+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.083 seconds
[2023-07-20T11:48:44.774+0000] {processor.py:153} INFO - Started process (PID=1852) to work on /opt/airflow/dags/main.py
[2023-07-20T11:48:44.777+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T11:48:44.779+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:48:44.779+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T11:48:44.823+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:48:44.820+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 4, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T11:48:44.825+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T11:48:44.856+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.089 seconds
[2023-07-20T11:49:15.029+0000] {processor.py:153} INFO - Started process (PID=1885) to work on /opt/airflow/dags/main.py
[2023-07-20T11:49:15.033+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T11:49:15.035+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:49:15.035+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T11:49:15.081+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:49:15.078+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 4, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T11:49:15.083+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T11:49:15.114+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.089 seconds
[2023-07-20T11:49:45.202+0000] {processor.py:153} INFO - Started process (PID=1932) to work on /opt/airflow/dags/main.py
[2023-07-20T11:49:45.205+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T11:49:45.207+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:49:45.206+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T11:49:45.251+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:49:45.248+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 4, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T11:49:45.253+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T11:49:45.283+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.085 seconds
[2023-07-20T11:50:15.482+0000] {processor.py:153} INFO - Started process (PID=1964) to work on /opt/airflow/dags/main.py
[2023-07-20T11:50:15.485+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T11:50:15.487+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:50:15.486+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T11:50:15.528+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:50:15.525+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 4, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T11:50:15.529+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T11:50:15.552+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.074 seconds
[2023-07-20T11:50:45.657+0000] {processor.py:153} INFO - Started process (PID=2011) to work on /opt/airflow/dags/main.py
[2023-07-20T11:50:45.660+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T11:50:45.662+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:50:45.662+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T11:50:45.704+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:50:45.700+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 4, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T11:50:45.705+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T11:50:45.729+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.077 seconds
[2023-07-20T11:51:15.916+0000] {processor.py:153} INFO - Started process (PID=2044) to work on /opt/airflow/dags/main.py
[2023-07-20T11:51:15.919+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T11:51:15.923+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:51:15.922+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T11:51:15.981+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:51:15.975+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 4, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T11:51:15.985+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T11:51:16.025+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.116 seconds
[2023-07-20T11:51:46.119+0000] {processor.py:153} INFO - Started process (PID=2091) to work on /opt/airflow/dags/main.py
[2023-07-20T11:51:46.121+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T11:51:46.123+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:51:46.122+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T11:51:46.158+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:51:46.156+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 4, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T11:51:46.161+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T11:51:46.189+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.074 seconds
[2023-07-20T11:52:16.371+0000] {processor.py:153} INFO - Started process (PID=2124) to work on /opt/airflow/dags/main.py
[2023-07-20T11:52:16.374+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T11:52:16.376+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:52:16.376+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T11:52:16.411+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:52:16.409+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 4, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T11:52:16.413+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T11:52:16.435+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.069 seconds
[2023-07-20T11:52:46.551+0000] {processor.py:153} INFO - Started process (PID=2164) to work on /opt/airflow/dags/main.py
[2023-07-20T11:52:46.554+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T11:52:46.556+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:52:46.556+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T11:52:46.592+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:52:46.588+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 4, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T11:52:46.595+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T11:52:46.618+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.071 seconds
[2023-07-20T11:53:16.773+0000] {processor.py:153} INFO - Started process (PID=2204) to work on /opt/airflow/dags/main.py
[2023-07-20T11:53:16.775+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T11:53:16.777+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:53:16.777+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T11:53:16.823+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:53:16.820+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 4, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T11:53:16.825+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T11:53:16.852+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.084 seconds
[2023-07-20T11:53:25.857+0000] {processor.py:153} INFO - Started process (PID=2223) to work on /opt/airflow/dags/main.py
[2023-07-20T11:53:25.860+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T11:53:25.862+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:53:25.862+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T11:53:25.925+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:53:25.922+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 6, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T11:53:25.927+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T11:53:25.951+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.099 seconds
[2023-07-20T11:53:26.940+0000] {processor.py:153} INFO - Started process (PID=2228) to work on /opt/airflow/dags/main.py
[2023-07-20T11:53:26.942+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T11:53:26.944+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:53:26.944+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T11:53:26.990+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:53:26.987+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 6, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T11:53:26.994+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T11:53:27.014+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.077 seconds
[2023-07-20T11:53:28.004+0000] {processor.py:153} INFO - Started process (PID=2233) to work on /opt/airflow/dags/main.py
[2023-07-20T11:53:28.006+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T11:53:28.008+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:53:28.008+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T11:53:28.057+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:53:28.053+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 6, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T11:53:28.058+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T11:53:28.083+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.082 seconds
