[2023-07-20T11:45:13.290+0000] {processor.py:153} INFO - Started process (PID=1579) to work on /opt/airflow/dags/main.py
[2023-07-20T11:45:13.292+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T11:45:13.294+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:45:13.294+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T11:45:13.377+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:45:13.373+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 4, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T11:45:13.379+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T11:45:13.401+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.117 seconds
[2023-07-20T11:45:43.477+0000] {processor.py:153} INFO - Started process (PID=1612) to work on /opt/airflow/dags/main.py
[2023-07-20T11:45:43.480+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T11:45:43.482+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:45:43.481+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T11:45:43.520+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:45:43.517+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 4, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T11:45:43.521+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T11:45:43.546+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.075 seconds
[2023-07-20T11:46:13.751+0000] {processor.py:153} INFO - Started process (PID=1659) to work on /opt/airflow/dags/main.py
[2023-07-20T11:46:13.753+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T11:46:13.754+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:46:13.754+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T11:46:13.785+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:46:13.782+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 4, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T11:46:13.786+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T11:46:13.808+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.060 seconds
[2023-07-20T11:46:43.937+0000] {processor.py:153} INFO - Started process (PID=1692) to work on /opt/airflow/dags/main.py
[2023-07-20T11:46:43.941+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T11:46:43.943+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:46:43.942+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T11:46:43.979+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:46:43.976+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 4, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T11:46:43.981+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T11:46:44.001+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.068 seconds
[2023-07-20T11:47:14.121+0000] {processor.py:153} INFO - Started process (PID=1739) to work on /opt/airflow/dags/main.py
[2023-07-20T11:47:14.124+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T11:47:14.126+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:47:14.126+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T11:47:14.167+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:47:14.164+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 4, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T11:47:14.169+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T11:47:14.195+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.078 seconds
[2023-07-20T11:47:44.339+0000] {processor.py:153} INFO - Started process (PID=1772) to work on /opt/airflow/dags/main.py
[2023-07-20T11:47:44.342+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T11:47:44.344+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:47:44.344+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T11:47:44.382+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:47:44.379+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 4, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T11:47:44.383+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T11:47:44.409+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.075 seconds
[2023-07-20T11:48:14.591+0000] {processor.py:153} INFO - Started process (PID=1819) to work on /opt/airflow/dags/main.py
[2023-07-20T11:48:14.594+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T11:48:14.597+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:48:14.597+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T11:48:14.640+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:48:14.636+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 4, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T11:48:14.642+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T11:48:14.670+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.083 seconds
[2023-07-20T11:48:44.774+0000] {processor.py:153} INFO - Started process (PID=1852) to work on /opt/airflow/dags/main.py
[2023-07-20T11:48:44.777+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T11:48:44.779+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:48:44.779+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T11:48:44.823+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:48:44.820+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 4, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T11:48:44.825+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T11:48:44.856+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.089 seconds
[2023-07-20T11:49:15.029+0000] {processor.py:153} INFO - Started process (PID=1885) to work on /opt/airflow/dags/main.py
[2023-07-20T11:49:15.033+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T11:49:15.035+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:49:15.035+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T11:49:15.081+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:49:15.078+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 4, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T11:49:15.083+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T11:49:15.114+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.089 seconds
[2023-07-20T11:49:45.202+0000] {processor.py:153} INFO - Started process (PID=1932) to work on /opt/airflow/dags/main.py
[2023-07-20T11:49:45.205+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T11:49:45.207+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:49:45.206+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T11:49:45.251+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:49:45.248+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 4, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T11:49:45.253+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T11:49:45.283+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.085 seconds
[2023-07-20T11:50:15.482+0000] {processor.py:153} INFO - Started process (PID=1964) to work on /opt/airflow/dags/main.py
[2023-07-20T11:50:15.485+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T11:50:15.487+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:50:15.486+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T11:50:15.528+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:50:15.525+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 4, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T11:50:15.529+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T11:50:15.552+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.074 seconds
[2023-07-20T11:50:45.657+0000] {processor.py:153} INFO - Started process (PID=2011) to work on /opt/airflow/dags/main.py
[2023-07-20T11:50:45.660+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T11:50:45.662+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:50:45.662+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T11:50:45.704+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:50:45.700+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 4, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T11:50:45.705+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T11:50:45.729+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.077 seconds
[2023-07-20T11:51:15.916+0000] {processor.py:153} INFO - Started process (PID=2044) to work on /opt/airflow/dags/main.py
[2023-07-20T11:51:15.919+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T11:51:15.923+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:51:15.922+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T11:51:15.981+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:51:15.975+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 4, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T11:51:15.985+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T11:51:16.025+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.116 seconds
[2023-07-20T11:51:46.119+0000] {processor.py:153} INFO - Started process (PID=2091) to work on /opt/airflow/dags/main.py
[2023-07-20T11:51:46.121+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T11:51:46.123+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:51:46.122+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T11:51:46.158+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:51:46.156+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 4, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T11:51:46.161+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T11:51:46.189+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.074 seconds
[2023-07-20T11:52:16.371+0000] {processor.py:153} INFO - Started process (PID=2124) to work on /opt/airflow/dags/main.py
[2023-07-20T11:52:16.374+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T11:52:16.376+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:52:16.376+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T11:52:16.411+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:52:16.409+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 4, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T11:52:16.413+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T11:52:16.435+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.069 seconds
[2023-07-20T11:52:46.551+0000] {processor.py:153} INFO - Started process (PID=2164) to work on /opt/airflow/dags/main.py
[2023-07-20T11:52:46.554+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T11:52:46.556+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:52:46.556+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T11:52:46.592+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:52:46.588+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 4, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T11:52:46.595+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T11:52:46.618+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.071 seconds
[2023-07-20T11:53:16.773+0000] {processor.py:153} INFO - Started process (PID=2204) to work on /opt/airflow/dags/main.py
[2023-07-20T11:53:16.775+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T11:53:16.777+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:53:16.777+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T11:53:16.823+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:53:16.820+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 4, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T11:53:16.825+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T11:53:16.852+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.084 seconds
[2023-07-20T11:53:25.857+0000] {processor.py:153} INFO - Started process (PID=2223) to work on /opt/airflow/dags/main.py
[2023-07-20T11:53:25.860+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T11:53:25.862+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:53:25.862+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T11:53:25.925+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:53:25.922+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 6, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T11:53:25.927+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T11:53:25.951+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.099 seconds
[2023-07-20T11:53:26.940+0000] {processor.py:153} INFO - Started process (PID=2228) to work on /opt/airflow/dags/main.py
[2023-07-20T11:53:26.942+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T11:53:26.944+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:53:26.944+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T11:53:26.990+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:53:26.987+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 6, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T11:53:26.994+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T11:53:27.014+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.077 seconds
[2023-07-20T11:53:28.004+0000] {processor.py:153} INFO - Started process (PID=2233) to work on /opt/airflow/dags/main.py
[2023-07-20T11:53:28.006+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T11:53:28.008+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:53:28.008+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T11:53:28.057+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:53:28.053+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 6, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T11:53:28.058+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T11:53:28.083+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.082 seconds
[2023-07-20T11:53:58.306+0000] {processor.py:153} INFO - Started process (PID=2266) to work on /opt/airflow/dags/main.py
[2023-07-20T11:53:58.308+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T11:53:58.310+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:53:58.310+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T11:53:58.358+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:53:58.354+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 6, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T11:53:58.360+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T11:53:58.389+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.089 seconds
[2023-07-20T11:54:28.484+0000] {processor.py:153} INFO - Started process (PID=2314) to work on /opt/airflow/dags/main.py
[2023-07-20T11:54:28.486+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T11:54:28.488+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:54:28.488+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T11:54:28.529+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:54:28.526+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 6, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T11:54:28.532+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T11:54:28.555+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.078 seconds
[2023-07-20T11:54:58.732+0000] {processor.py:153} INFO - Started process (PID=2348) to work on /opt/airflow/dags/main.py
[2023-07-20T11:54:58.734+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T11:54:58.736+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:54:58.736+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T11:54:58.780+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:54:58.777+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 6, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T11:54:58.782+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T11:54:58.806+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.078 seconds
[2023-07-20T11:55:28.941+0000] {processor.py:153} INFO - Started process (PID=2395) to work on /opt/airflow/dags/main.py
[2023-07-20T11:55:28.943+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T11:55:28.945+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:55:28.945+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T11:55:28.989+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:55:28.986+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 6, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T11:55:28.991+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T11:55:29.016+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.080 seconds
[2023-07-20T11:55:59.135+0000] {processor.py:153} INFO - Started process (PID=2428) to work on /opt/airflow/dags/main.py
[2023-07-20T11:55:59.138+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T11:55:59.140+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:55:59.139+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T11:55:59.180+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:55:59.178+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 6, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T11:55:59.183+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T11:55:59.204+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.074 seconds
[2023-07-20T11:56:03.212+0000] {processor.py:153} INFO - Started process (PID=2433) to work on /opt/airflow/dags/main.py
[2023-07-20T11:56:03.215+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T11:56:03.217+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:56:03.217+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T11:56:03.236+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:56:03.234+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 4, in <module>
    from airflow import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.7/site-packages/airflow/__init__.py)
[2023-07-20T11:56:03.237+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T11:56:03.261+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.055 seconds
[2023-07-20T11:56:33.435+0000] {processor.py:153} INFO - Started process (PID=2480) to work on /opt/airflow/dags/main.py
[2023-07-20T11:56:33.438+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T11:56:33.439+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:56:33.439+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T11:56:33.453+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:56:33.450+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 4, in <module>
    from airflow import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow' (/home/airflow/.local/lib/python3.7/site-packages/airflow/__init__.py)
[2023-07-20T11:56:33.454+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T11:56:33.487+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.057 seconds
[2023-07-20T11:56:35.465+0000] {processor.py:153} INFO - Started process (PID=2485) to work on /opt/airflow/dags/main.py
[2023-07-20T11:56:35.468+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T11:56:35.470+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:56:35.470+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T11:56:35.527+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:56:35.524+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 6, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T11:56:35.529+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T11:56:35.553+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.095 seconds
[2023-07-20T11:57:05.710+0000] {processor.py:153} INFO - Started process (PID=2518) to work on /opt/airflow/dags/main.py
[2023-07-20T11:57:05.713+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T11:57:05.716+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:57:05.716+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T11:57:05.767+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:57:05.764+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 6, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T11:57:05.769+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T11:57:05.798+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.094 seconds
[2023-07-20T11:57:35.894+0000] {processor.py:153} INFO - Started process (PID=2565) to work on /opt/airflow/dags/main.py
[2023-07-20T11:57:35.896+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T11:57:35.898+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:57:35.898+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T11:57:35.940+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:57:35.937+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 6, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T11:57:35.944+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T11:57:35.972+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.083 seconds
[2023-07-20T11:58:06.143+0000] {processor.py:153} INFO - Started process (PID=2598) to work on /opt/airflow/dags/main.py
[2023-07-20T11:58:06.145+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T11:58:06.147+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:58:06.147+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T11:58:06.187+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:58:06.184+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 6, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T11:58:06.190+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T11:58:06.213+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.074 seconds
[2023-07-20T11:58:36.323+0000] {processor.py:153} INFO - Started process (PID=2645) to work on /opt/airflow/dags/main.py
[2023-07-20T11:58:36.325+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T11:58:36.327+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:58:36.327+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T11:58:36.370+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:58:36.367+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 6, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T11:58:36.371+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T11:58:36.395+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.077 seconds
[2023-07-20T11:59:06.552+0000] {processor.py:153} INFO - Started process (PID=2678) to work on /opt/airflow/dags/main.py
[2023-07-20T11:59:06.554+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T11:59:06.556+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:59:06.556+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T11:59:06.596+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:59:06.593+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 6, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T11:59:06.597+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T11:59:06.622+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.075 seconds
[2023-07-20T11:59:36.730+0000] {processor.py:153} INFO - Started process (PID=2720) to work on /opt/airflow/dags/main.py
[2023-07-20T11:59:36.732+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T11:59:36.733+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:59:36.733+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T11:59:36.767+0000] {logging_mixin.py:137} INFO - [2023-07-20T11:59:36.764+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 6, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T11:59:36.769+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T11:59:36.793+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.067 seconds
[2023-07-20T12:00:06.969+0000] {processor.py:153} INFO - Started process (PID=2758) to work on /opt/airflow/dags/main.py
[2023-07-20T12:00:06.971+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T12:00:06.973+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:00:06.973+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T12:00:07.006+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:00:07.003+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 6, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T12:00:07.007+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T12:00:07.027+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.061 seconds
[2023-07-20T12:00:37.185+0000] {processor.py:153} INFO - Started process (PID=2791) to work on /opt/airflow/dags/main.py
[2023-07-20T12:00:37.187+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T12:00:37.189+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:00:37.189+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T12:00:37.236+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:00:37.232+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 6, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T12:00:37.237+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T12:00:37.266+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.087 seconds
[2023-07-20T12:01:07.363+0000] {processor.py:153} INFO - Started process (PID=2838) to work on /opt/airflow/dags/main.py
[2023-07-20T12:01:07.365+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T12:01:07.366+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:01:07.366+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T12:01:07.408+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:01:07.405+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 6, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T12:01:07.409+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T12:01:07.438+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.080 seconds
[2023-07-20T12:01:37.590+0000] {processor.py:153} INFO - Started process (PID=2871) to work on /opt/airflow/dags/main.py
[2023-07-20T12:01:37.593+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T12:01:37.595+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:01:37.594+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T12:01:37.626+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:01:37.624+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 6, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T12:01:37.628+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T12:01:37.647+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.061 seconds
[2023-07-20T12:02:07.739+0000] {processor.py:153} INFO - Started process (PID=2919) to work on /opt/airflow/dags/main.py
[2023-07-20T12:02:07.742+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T12:02:07.744+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:02:07.744+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T12:02:07.781+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:02:07.778+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 6, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T12:02:07.783+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T12:02:07.814+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.079 seconds
[2023-07-20T12:02:37.932+0000] {processor.py:153} INFO - Started process (PID=2952) to work on /opt/airflow/dags/main.py
[2023-07-20T12:02:37.937+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T12:02:37.939+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:02:37.939+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T12:02:38.002+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:02:37.997+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 6, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T12:02:38.004+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T12:02:38.040+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.115 seconds
[2023-07-20T12:03:08.135+0000] {processor.py:153} INFO - Started process (PID=2985) to work on /opt/airflow/dags/main.py
[2023-07-20T12:03:08.139+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T12:03:08.141+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:03:08.141+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T12:03:08.176+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:03:08.173+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 6, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T12:03:08.178+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T12:03:08.202+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.071 seconds
[2023-07-20T12:03:38.379+0000] {processor.py:153} INFO - Started process (PID=3032) to work on /opt/airflow/dags/main.py
[2023-07-20T12:03:38.381+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T12:03:38.384+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:03:38.384+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T12:03:38.429+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:03:38.427+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 6, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T12:03:38.431+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T12:03:38.456+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.082 seconds
[2023-07-20T12:04:08.581+0000] {processor.py:153} INFO - Started process (PID=3065) to work on /opt/airflow/dags/main.py
[2023-07-20T12:04:08.583+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T12:04:08.585+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:04:08.585+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T12:04:08.625+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:04:08.623+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 6, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T12:04:08.627+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T12:04:08.651+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.075 seconds
[2023-07-20T12:04:38.798+0000] {processor.py:153} INFO - Started process (PID=3112) to work on /opt/airflow/dags/main.py
[2023-07-20T12:04:38.800+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T12:04:38.803+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:04:38.803+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T12:04:38.842+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:04:38.840+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 6, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T12:04:38.844+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T12:04:38.868+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.074 seconds
[2023-07-20T12:05:08.986+0000] {processor.py:153} INFO - Started process (PID=3145) to work on /opt/airflow/dags/main.py
[2023-07-20T12:05:08.988+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T12:05:08.990+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:05:08.990+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T12:05:09.030+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:05:09.028+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 6, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T12:05:09.032+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T12:05:09.057+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.078 seconds
[2023-07-20T12:05:39.263+0000] {processor.py:153} INFO - Started process (PID=3192) to work on /opt/airflow/dags/main.py
[2023-07-20T12:05:39.265+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T12:05:39.267+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:05:39.266+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T12:05:39.300+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:05:39.297+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 6, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T12:05:39.302+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T12:05:39.324+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.064 seconds
[2023-07-20T12:06:09.443+0000] {processor.py:153} INFO - Started process (PID=3225) to work on /opt/airflow/dags/main.py
[2023-07-20T12:06:09.445+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T12:06:09.446+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:06:09.446+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T12:06:09.484+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:06:09.481+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 6, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T12:06:09.486+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T12:06:09.509+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.070 seconds
[2023-07-20T12:06:39.674+0000] {processor.py:153} INFO - Started process (PID=3265) to work on /opt/airflow/dags/main.py
[2023-07-20T12:06:39.676+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T12:06:39.677+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:06:39.677+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T12:06:39.713+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:06:39.710+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 6, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T12:06:39.715+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T12:06:39.739+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.068 seconds
[2023-07-20T12:07:09.846+0000] {processor.py:153} INFO - Started process (PID=3305) to work on /opt/airflow/dags/main.py
[2023-07-20T12:07:09.848+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T12:07:09.849+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:07:09.849+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T12:07:09.886+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:07:09.882+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 6, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T12:07:09.887+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T12:07:09.911+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.069 seconds
[2023-07-20T12:07:40.099+0000] {processor.py:153} INFO - Started process (PID=3338) to work on /opt/airflow/dags/main.py
[2023-07-20T12:07:40.108+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T12:07:40.129+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:07:40.129+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T12:07:40.173+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:07:40.170+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 6, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T12:07:40.177+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T12:07:40.205+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.110 seconds
[2023-07-20T12:08:10.275+0000] {processor.py:153} INFO - Started process (PID=3386) to work on /opt/airflow/dags/main.py
[2023-07-20T12:08:10.278+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T12:08:10.280+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:08:10.280+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T12:08:10.323+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:08:10.320+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 6, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T12:08:10.325+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T12:08:10.350+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.080 seconds
[2023-07-20T12:08:40.550+0000] {processor.py:153} INFO - Started process (PID=3419) to work on /opt/airflow/dags/main.py
[2023-07-20T12:08:40.552+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T12:08:40.554+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:08:40.554+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T12:08:40.593+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:08:40.590+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 6, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T12:08:40.595+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T12:08:40.618+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.073 seconds
[2023-07-20T12:09:10.751+0000] {processor.py:153} INFO - Started process (PID=3466) to work on /opt/airflow/dags/main.py
[2023-07-20T12:09:10.753+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T12:09:10.755+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:09:10.755+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T12:09:10.806+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:09:10.802+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 6, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T12:09:10.809+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T12:09:10.840+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.095 seconds
[2023-07-20T12:09:40.955+0000] {processor.py:153} INFO - Started process (PID=3499) to work on /opt/airflow/dags/main.py
[2023-07-20T12:09:40.958+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T12:09:40.960+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:09:40.960+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T12:09:41.007+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:09:41.004+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 6, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T12:09:41.009+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T12:09:41.036+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.087 seconds
[2023-07-20T12:10:11.198+0000] {processor.py:153} INFO - Started process (PID=3533) to work on /opt/airflow/dags/main.py
[2023-07-20T12:10:11.200+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T12:10:11.204+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:10:11.203+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T12:10:11.260+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:10:11.256+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 6, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T12:10:11.262+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T12:10:11.290+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.102 seconds
[2023-07-20T12:10:41.421+0000] {processor.py:153} INFO - Started process (PID=3580) to work on /opt/airflow/dags/main.py
[2023-07-20T12:10:41.422+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T12:10:41.424+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:10:41.424+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T12:10:41.459+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:10:41.456+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 6, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T12:10:41.462+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T12:10:41.487+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.070 seconds
[2023-07-20T12:11:11.677+0000] {processor.py:153} INFO - Started process (PID=3613) to work on /opt/airflow/dags/main.py
[2023-07-20T12:11:11.679+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T12:11:11.681+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:11:11.681+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T12:11:11.720+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:11:11.717+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 6, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T12:11:11.722+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T12:11:11.744+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.072 seconds
[2023-07-20T12:11:41.858+0000] {processor.py:153} INFO - Started process (PID=3660) to work on /opt/airflow/dags/main.py
[2023-07-20T12:11:41.860+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T12:11:41.862+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:11:41.862+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T12:11:41.902+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:11:41.900+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 6, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T12:11:41.904+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T12:11:41.928+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.075 seconds
[2023-07-20T12:12:12.080+0000] {processor.py:153} INFO - Started process (PID=3692) to work on /opt/airflow/dags/main.py
[2023-07-20T12:12:12.083+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T12:12:12.086+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:12:12.086+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T12:12:12.125+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:12:12.122+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 6, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T12:12:12.128+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T12:12:12.151+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.075 seconds
[2023-07-20T12:12:42.271+0000] {processor.py:153} INFO - Started process (PID=3734) to work on /opt/airflow/dags/main.py
[2023-07-20T12:12:42.273+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T12:12:42.275+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:12:42.275+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T12:12:42.309+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:12:42.306+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 6, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T12:12:42.310+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T12:12:42.334+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.067 seconds
[2023-07-20T12:13:12.502+0000] {processor.py:153} INFO - Started process (PID=3772) to work on /opt/airflow/dags/main.py
[2023-07-20T12:13:12.505+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T12:13:12.507+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:13:12.507+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T12:13:12.556+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:13:12.553+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 6, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T12:13:12.558+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T12:13:12.589+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.092 seconds
[2023-07-20T12:13:42.675+0000] {processor.py:153} INFO - Started process (PID=3805) to work on /opt/airflow/dags/main.py
[2023-07-20T12:13:42.678+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T12:13:42.680+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:13:42.679+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T12:13:42.727+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:13:42.724+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 6, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T12:13:42.729+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T12:13:42.758+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.088 seconds
[2023-07-20T12:14:12.930+0000] {processor.py:153} INFO - Started process (PID=3851) to work on /opt/airflow/dags/main.py
[2023-07-20T12:14:12.932+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T12:14:12.934+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:14:12.934+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T12:14:12.979+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:14:12.976+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 6, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T12:14:12.980+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T12:14:13.004+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.078 seconds
[2023-07-20T12:14:43.105+0000] {processor.py:153} INFO - Started process (PID=3884) to work on /opt/airflow/dags/main.py
[2023-07-20T12:14:43.108+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T12:14:43.109+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:14:43.109+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T12:14:43.159+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:14:43.156+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 6, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T12:14:43.161+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T12:14:43.186+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.088 seconds
[2023-07-20T12:15:13.364+0000] {processor.py:153} INFO - Started process (PID=3931) to work on /opt/airflow/dags/main.py
[2023-07-20T12:15:13.367+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T12:15:13.369+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:15:13.369+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T12:15:13.410+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:15:13.407+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 6, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T12:15:13.412+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T12:15:13.434+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.074 seconds
[2023-07-20T12:15:43.631+0000] {processor.py:153} INFO - Started process (PID=3969) to work on /opt/airflow/dags/main.py
[2023-07-20T12:15:43.633+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T12:15:43.636+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:15:43.635+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T12:15:43.676+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:15:43.673+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 6, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T12:15:43.677+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T12:15:43.702+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.077 seconds
[2023-07-20T12:16:13.910+0000] {processor.py:153} INFO - Started process (PID=4021) to work on /opt/airflow/dags/main.py
[2023-07-20T12:16:13.913+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T12:16:13.916+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:16:13.915+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T12:16:13.967+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:16:13.963+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 6, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T12:16:13.969+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T12:16:13.999+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.096 seconds
[2023-07-20T12:16:44.259+0000] {processor.py:153} INFO - Started process (PID=4091) to work on /opt/airflow/dags/main.py
[2023-07-20T12:16:44.261+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T12:16:44.263+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:16:44.263+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T12:16:44.305+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:16:44.302+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 6, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T12:16:44.307+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T12:16:44.331+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.078 seconds
[2023-07-20T12:17:14.537+0000] {processor.py:153} INFO - Started process (PID=4138) to work on /opt/airflow/dags/main.py
[2023-07-20T12:17:14.540+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T12:17:14.543+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:17:14.542+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T12:17:14.590+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:17:14.586+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 6, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T12:17:14.592+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T12:17:14.620+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.088 seconds
[2023-07-20T12:17:44.819+0000] {processor.py:153} INFO - Started process (PID=4181) to work on /opt/airflow/dags/main.py
[2023-07-20T12:17:44.822+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T12:17:44.824+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:17:44.824+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T12:17:44.867+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:17:44.864+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 6, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T12:17:44.868+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T12:17:44.894+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.080 seconds
[2023-07-20T12:18:15.107+0000] {processor.py:153} INFO - Started process (PID=4219) to work on /opt/airflow/dags/main.py
[2023-07-20T12:18:15.110+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T12:18:15.112+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:18:15.111+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T12:18:15.153+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:18:15.150+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 6, in <module>
    from airflow.providers.snowflake.sensors.sql import SnowflakeSQLSensor
ModuleNotFoundError: No module named 'airflow.providers.snowflake.sensors'
[2023-07-20T12:18:15.154+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2023-07-20T12:18:15.178+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.077 seconds
[2023-07-20T12:18:56.586+0000] {processor.py:153} INFO - Started process (PID=4285) to work on /opt/airflow/dags/main.py
[2023-07-20T12:18:56.590+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T12:18:56.594+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:18:56.593+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T12:18:56.696+0000] {logging_mixin.py:137} WARNING - /home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py:243 RemovedInAirflow3Warning: provide_context is deprecated as of 2.0 and is no longer required
[2023-07-20T12:18:56.711+0000] {processor.py:753} INFO - DAG(s) dict_keys(['long_running_queries_alert']) retrieved from /opt/airflow/dags/main.py
[2023-07-20T12:18:56.838+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:18:56.838+0000] {dag.py:2676} INFO - Sync 1 DAGs
[2023-07-20T12:18:56.906+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.326 seconds
[2023-07-20T12:19:26.992+0000] {processor.py:153} INFO - Started process (PID=4318) to work on /opt/airflow/dags/main.py
[2023-07-20T12:19:26.995+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2023-07-20T12:19:26.997+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:19:26.997+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2023-07-20T12:19:27.065+0000] {logging_mixin.py:137} WARNING - /home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py:243 RemovedInAirflow3Warning: provide_context is deprecated as of 2.0 and is no longer required
[2023-07-20T12:19:27.078+0000] {processor.py:753} INFO - DAG(s) dict_keys(['long_running_queries_alert']) retrieved from /opt/airflow/dags/main.py
[2023-07-20T12:19:27.145+0000] {logging_mixin.py:137} INFO - [2023-07-20T12:19:27.145+0000] {dag.py:2676} INFO - Sync 1 DAGs
[2023-07-20T12:19:27.233+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.247 seconds
